doc-warnings: true
test-warnings: true
strictness: veryhigh
max-line-length: 120
autodetect: true
python-targets:
  - 3
ignore-paths:
  - docs
  - examples
  - tests
pep257:
  disable:
    - D205
    - D210
