# This file is autogenerated by edgy.project code generator.
# All changes will be overwritten.

from setuptools import setup, find_packages
from codecs import open
from os import path

here = path.abspath(path.dirname(__file__))

# Py3 compatibility hacks, borrowed from IPython.
try:
    execfile
except NameError:

    def execfile(fname, globs, locs=None):
        locs = locs or globs
        exec(compile(open(fname).read(), fname, "exec"), globs, locs)


# Get the long description from the README file
with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    long_description = f.read()

# Get the classifiers from the classifiers file
tolines = lambda c: list(filter(None, map(lambda s: s.strip(), c.split('\n'))))
with open(path.join(here, 'classifiers.txt'), encoding='utf-8') as f:
    classifiers = tolines(f.read())

version_ns = {}
try:
    execfile(path.join(here, 'bonobo/_version.py'), version_ns)
except EnvironmentError:
    version = 'dev'
else:
    version = version_ns.get('__version__', 'dev')

setup(
    name='bonobo',
    description=('Bonobo, a simple, modern and atomic extract-transform-load toolkit for '
                 'python 3.5+.'),
    license='Apache License, Version 2.0',
    install_requires=[
        'colorama >=0.3,<1.0', 'fs >=2.0,<3.0', 'psutil >=5.2,<6.0', 'requests >=2.0,<3.0', 'stevedore >=1.21,<2.0'
    ],
    version=version,
    long_description=long_description,
    classifiers=classifiers,
    packages=find_packages(exclude=['ez_setup', 'example', 'test']),
    include_package_data=True,
    data_files=[
        (
            'share/jupyter/nbextensions/bonobo-jupyter', [
                'bonobo/ext/jupyter/static/extension.js', 'bonobo/ext/jupyter/static/index.js',
                'bonobo/ext/jupyter/static/index.js.map'
            ]
        )
    ],
    extras_require={
        'dev': [
            'coverage >=4,<5', 'pylint >=1,<2', 'pytest >=3,<4', 'pytest-cov >=2,<3', 'pytest-timeout >=1,<2', 'sphinx',
            'sphinx_rtd_theme', 'yapf'
        ],
        'jupyter': ['jupyter >=1.0,<1.1', 'ipywidgets >=6.0.0.beta5']
    },
    entry_points={
        'bonobo.commands': [
            'init = bonobo.commands.init:register', 'run = bonobo.commands.run:register',
            'version = bonobo.commands.version:register'
        ],
        'console_scripts': ['bonobo = bonobo.commands:entrypoint'],
        'edgy.project.features': ['bonobo = '
                                  'bonobo.ext.edgy.project.feature:BonoboFeature']
    },
    url='https://www.bonobo-project.org/',
    download_url='https://github.com/python-bonobo/bonobo/tarball/{version}'.format(version=version),
)
